### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by esabol**
Minor tweaks: Added a missing period. Removed an extra space. Capitalize PlayStation.

### CODE REVIEW

**Comment by dhleong** [comment]
Thanks! The lower-cased `playstation` is actually a stylistic choice to keep that line in all lower-case, but the other changes look fine.

**Comment by esabol** [comment]
Cool. Thanks.

**Comment by esabol** [comment]
Ok, I have reverted the change to “playstation”. Done.

**Comment by dhleong** [comment]
Thanks! :)

**Pull request merged**
